# ------------------------------------------------------------------------------
# MONOGRAM Config
# ------------------------------------------------------------------------------
# Jekyll Configuration / Copyright (C) 2017 Monogram, LLC. All rights reserved.
# ------------------------------------------------------------------------------

# Build settings
source: _source
destination: _deploy
permalink: pretty
markdown: kramdown
# incremental: true

exclude:
  - main.built.js

plugins: [jekyll-email-protect, jekyll-last-modified-at]

filePath: /docs/examples/files/uploads

# Client Information
# ------------------------------------------------------------------------------

# Basic
name: Monogram
shortname: m
legal: Monogram, LLC
domain: "http://monogram.design/"

# Contact
phone: 415 997 7754
email: hello@monogram.design

# Meta
description: "Design agency for the human experience. We design experiences that improve lives and move people."
keywords: "design,atlanta,web,agency,graphic,print,marketing"

google-analytics: false
google-verification: Oxo4aJhF8Wt5tVkJ3K1jFWyPQGcWAiNneo-4lD4v3-0

chanhgefreq: weekly