# Monogram - Jekyll Configuration
# ---------------------------------------------------------

name: Monogram


# Build settings
source: _source
destination: _deploy
permalink: pretty
markdown: kramdown
# incremental: true

exclude:
  - main.built.js

gems:
  - jekyll-email-protect
  - jekyll-last-modified-at

filePath: /docs/examples/files/uploads